package com.gw.zph.base.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gw.zph.base.db.AddressBean;
import com.gw.zph.base.db.dao.OffLineLatLngInfo;

import com.gw.zph.base.db.dao.AddressBeanDao;
import com.gw.zph.base.db.dao.OffLineLatLngInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig addressBeanDaoConfig;
    private final DaoConfig offLineLatLngInfoDaoConfig;

    private final AddressBeanDao addressBeanDao;
    private final OffLineLatLngInfoDao offLineLatLngInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        addressBeanDaoConfig = daoConfigMap.get(AddressBeanDao.class).clone();
        addressBeanDaoConfig.initIdentityScope(type);

        offLineLatLngInfoDaoConfig = daoConfigMap.get(OffLineLatLngInfoDao.class).clone();
        offLineLatLngInfoDaoConfig.initIdentityScope(type);

        addressBeanDao = new AddressBeanDao(addressBeanDaoConfig, this);
        offLineLatLngInfoDao = new OffLineLatLngInfoDao(offLineLatLngInfoDaoConfig, this);

        registerDao(AddressBean.class, addressBeanDao);
        registerDao(OffLineLatLngInfo.class, offLineLatLngInfoDao);
    }
    
    public void clear() {
        addressBeanDaoConfig.clearIdentityScope();
        offLineLatLngInfoDaoConfig.clearIdentityScope();
    }

    public AddressBeanDao getAddressBeanDao() {
        return addressBeanDao;
    }

    public OffLineLatLngInfoDao getOffLineLatLngInfoDao() {
        return offLineLatLngInfoDao;
    }

}
